### ISSUE TITLE
graphics showing increased use of tools

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/public-survey-info#57]
For the graphics showing learner pre-workshop and follow-up use of the tools taught at the workshop, it would be nice to have these combined in a single graphic with side-by-side bars showing learner pre- and post-usage. 

Would also be nice to have those bars scaled to percent of respondents rather than absolute response count for comparison.

**Comment by naupaka** [comment]
See PR #75 - I think that is what you want?

**Comment by kariljordan** [comment]
@naupaka Thank you for contributing to our report! I've been studying the code to understand how it works so that I can apply it to some other plots, and I have a question for you. The scale for this question on the pre survey is slightly different than the post survey:

Pre-Survey: I **had** not been using tools like these.
Post-Survey: I **have** not been using tools like these.

All of the other options (Less than once a year, weekly, daily, etc.) are exactly the same. In your code for the group_by() you use **key, value**, but shouldn't the values be identical? I'm getting this error: **attributes are not identical across measure variables; they will be dropped** and wondering if it's because the scale isn't identical (have vs. had).

The plot shows a bar for NAs which I thought shouldn't be there because I used **na.strings = ""** when I loaded the CSV. Also, the bar for less than once per year only shows up in blue for "after the workshop"...it looks like the bar for "before the workshop" didn't make it?

<img width="983" alt="screen shot 2017-05-02 at 10 34 51 am" src="https://cloud.githubusercontent.com/assets/21027863/25610319/12aef360-2f23-11e7-8235-7a53df6c15b1.png">

I pasted your code for the fix below, but of course the formatting got messed up. No rush on this. I'm actually teaching a workshop today so I'll be on and off (plus it's probably 5am where you are!)

data %>%
  select(Programming.Usage.Before.Workshop, Programming.Usage.Since.Workshop) %>%
  gather() %>%
  group_by(key, value) %>%
  tally() %>%
  filter(!is.na(value)) %>%
  mutate(value = factor(value, levels = programming)) %>%
  ggplot(aes(x = value, y = 100 * (n/sum(n)), fill = key)) +
    geom_bar(stat = "identity", position = "dodge") +
    scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                         width = 10,
                                                         simplify = FALSE),
                                                 paste,
                                                 collapse = "\n")) +
    theme_classic() +
    xlab("") +
    ylab("Percent of respondants") +
    scale_fill_discrete(name = "",
                        labels = c("Before workshop", "After workshop")) +
    ggtitle("Respondents' Programming Usage Increased") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 14)

(cc @ErinBecker)

**Comment by naupaka** [comment]
Hmmm, I think it has to do with perhaps trying to fix the factor levels in two different ways. Note that in the code below I comment out this line:

```r
#### skip this ####
# data$Programming.Usage.Before.Workshop = factor(data$Programming.Usage.Before.Workshop, levels = programming)
```

So, when I run this code and only this code:

```r
library("ggplot2")
library("dplyr")
library("tidyr")

# load data
data <- read.csv("2017-04-17-carpentry-long-term-assessment-survey-data-public.csv", na.strings = "")

# fix order of factor levels
programming <- c("I have not been using tools like these.", "Less than once per year.", "Several times per year.", "Monthly.", "Weekly.", "Daily.")
programming <- factor(programming)

#### skip this ####
# data$Programming.Usage.Before.Workshop = factor(data$Programming.Usage.Before.Workshop, levels = programming)

#Attempt to make a grouped bar plot of programming usage pre- and post-workshop

# Fix so pre- and post- responses match
levels(data$Programming.Usage.Before.Workshop)[2] <- "I have not been using tools like these."

data %>%
  select(Programming.Usage.Before.Workshop, Programming.Usage.Since.Workshop) %>%
  gather() %>%
  group_by(key, value) %>%
  tally() %>%
  filter(!is.na(value)) %>%
  mutate(value = factor(value, levels = programming)) %>%
  ggplot(aes(x = value, y = 100 * (n/sum(n)), fill = key)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_discrete(labels = function(x) lapply(strwrap(x,
                                                       width = 10,
                                                       simplify = FALSE),
                                               paste,
                                               collapse = "\n")) +
  theme_classic() +
  xlab("") +
  ylab("Percent of respondants") +
  scale_fill_discrete(name = "",
                      labels = c("Before workshop", "After workshop")) +
  ggtitle("Respondents' Programming Usage Increased") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_classic(base_size = 14)
```

I get this plot:

![image](https://cloud.githubusercontent.com/assets/1428071/25618759/10593d62-2efd-11e7-9dc8-dae59ffe0fa2.png)

**Comment by kariljordan** [comment]
Thank you so much @naupaka for clearing that up!
